CloudHRMS/Controllers/EmployeeController.cs
using CloudHRMS.DAO;
using CloudHRMS.Models.Entities;
using CloudHRMS.Models.ViewModels;
using CloudHRMS.Services;
using CloudHRMS.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers
{
    public class EmployeeController : Controller
    {
        //declare the private global variable for ApplicationDbContext
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IUserService _userService;

        //Constructor Dependency injection in here to call the ApplicationDbContext
        public EmployeeController(ApplicationDbContext applicationDbContext, IUserService userService)
        {
            _applicationDbContext = applicationDbContext;
            _userService = userService;
        }
        [Authorize(Roles = "HR")]
        public IActionResult Entry()
        {
            var employeeViewModel = new EmployeeViewModel();

            employeeViewModel.DepartmentsViewModel = _applicationDbContext.Departments.Where(w => w.IsActive).Select(s => new DepartmentViewModel
            {
                Id = s.Id,
                Code = s.Code
            }).ToList();
            employeeViewModel.PositionsViewModel = _applicationDbContext.Positions.Where(w => w.IsActive).Select(s => new PositionViewModel
            {
                Id = s.Id,
                Code = s.Code
            }).ToList();

            return View(employeeViewModel);//passing the employee viewModel to the related View
        }
        [Authorize(Roles = "HR")]
        [HttpPost]
        public async Task<IActionResult> Entry(EmployeeViewModel employeeViewModel)
        {
            try
            {

                string userId = await _userService.CreateUser(employeeViewModel.FullName, employeeViewModel.Email);
                if (string.IsNullOrEmpty(userId))
                {
                    TempData["Msg"] = "Error occur when user creationg process.";
                    TempData["IsOccurError"] = false;
                    return RedirectToAction("List");
                }
                //DTO: data transfer object from View Models to Entity
                EmployeeEntity employeeEntity = new EmployeeEntity()
                {
                    Id = Guid.NewGuid().ToString(),
                    No = employeeViewModel.No,
                    FullName = employeeViewModel.FullName,
                    DOB = DateTime.SpecifyKind(employeeViewModel.DOB, DateTimeKind.Utc),
                    DOE = DateTime.SpecifyKind(employeeViewModel.DOE, DateTimeKind.Utc),
                    Phone = employeeViewModel.Phone,
                    Address = employeeViewModel.Address,
                    Salary = employeeViewModel.Salary,
                    Gender = employeeViewModel.Gender,
                    Email = employeeViewModel.Email,
                    DOR = employeeViewModel.DOR is not null ? DateTime.SpecifyKind((DateTime)employeeViewModel.DOR, DateTimeKind.Utc) : null,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "System",
                    IsActive = true,
                    DepartmentId = employeeViewModel.DepartmentId,
                    PositionId = employeeViewModel.PositionId,
                    UserId = userId
                };
                _applicationDbContext.Employees.Add(employeeEntity);//adding the Entity to the context
                _applicationDbContext.SaveChanges();//actually save the connected database
                TempData["Msg"] = "Successfully created the record to the system";
                TempData["IsOccurError"] = false;
            }
            catch (Exception ex)
            {
                TempData["Msg"] = "Error Occur created the record to the system";
                TempData["IsOccurError"] = true;
            }
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            //DTO : Entity to View Model data exchange
            IList<EmployeeViewModel> employees = (from e in _applicationDbContext.Employees
                                                  join d in _applicationDbContext.Departments
                                                  on e.DepartmentId equals d.Id
                                                  join p in _applicationDbContext.Positions
                                                  on e.PositionId equals p.Id
                                                  where e.IsActive && p.IsActive && d.IsActive
                                                  select new EmployeeViewModel
                                                  {
                                                      Id = e.Id,
                                                      No = e.No,
                                                      FullName = e.FullName,
                                                      Email = e.Email,
                                                      Phone = e.Phone,
                                                      Address = e.Address,
                                                      Salary = e.Salary,
                                                      Gender = e.Gender,
                                                      DOB = e.DOB,
                                                      DOE = e.DOE,
                                                      DOR = e.DOR,
                                                      DepartmentId = e.DepartmentId,//CURD Process
                                                      PositionId = e.PositionId,//CURD Process
                                                      DepartmentInfo = d.Description,//to display UI List
                                                      PositonInfo = p.Description,//to display UI List
                                                      UserId = e.UserId
                                                  }).ToList();
            if (!User.IsInRole("HR"))
            {
                var loginedUser = _userService.FindByUserName(User.Identity.Name).Result;
                employees = employees.Where(u => u.UserId == loginedUser.Id).ToList();
            }
            return View(employees);//pass the viewModel object to the related view
        }
        [Authorize(Roles = "HR")]
        //port://host/employee/delete?id=10
        public IActionResult Delete(string Id)
        {
            try
            {
                var existingEmployee = _applicationDbContext.Employees.Where(w => w.Id == Id).SingleOrDefault();
                if (existingEmployee is not null)
                {
                    existingEmployee.IsActive = false;
                    _applicationDbContext.Update(existingEmployee);
                    _applicationDbContext.SaveChanges();
                    TempData["Msg"] = "Successfully Deleted the record from the system";
                    TempData["IsOccurError"] = false;
                }
            }
            catch (Exception e)
            {

                TempData["Msg"] = "Oh,Error occurs when deleting the record from the system.";
                TempData["IsOccurError"] = true;
            }
            return RedirectToAction("List");
        }
        [Authorize(Roles = "HR")]
        public IActionResult Edit(string Id)
        {

            var employeeViewModel = _applicationDbContext.Employees.Where(w => w.Id == Id).Select(s => new EmployeeViewModel
            {
                Id = s.Id,
                No = s.No,
                FullName = s.FullName,
                Email = s.Email,
                Phone = s.Phone,
                Address = s.Address,
                Salary = s.Salary,
                Gender = s.Gender,
                DOB = s.DOB,
                DOE = s.DOE,
                DOR = s.DOR,
                DepartmentId = s.DepartmentId,
                PositionId = s.PositionId
            }).SingleOrDefault();
            employeeViewModel.DepartmentsViewModel = _applicationDbContext.Departments.Where(w => w.IsActive).Select(s => new DepartmentViewModel
            {
                Id = s.Id,
                Code = s.Code
            }).ToList();
            employeeViewModel.PositionsViewModel = _applicationDbContext.Positions.Where(w => w.IsActive).Select(s => new PositionViewModel
            {
                Id = s.Id,
                Code = s.Code
            }).ToList();
            return View(employeeViewModel);
        }
        [Authorize(Roles = "HR")]
        [HttpPost]
        public IActionResult Update(EmployeeViewModel employeeViewModel)
        {
            try
            {
                //DTO: data transfer object from View Models to Entity
                var existingEmployeeEntity = _applicationDbContext.Employees.Find(employeeViewModel.Id);
                existingEmployeeEntity.No = employeeViewModel.No;
                existingEmployeeEntity.FullName = employeeViewModel.FullName;
                existingEmployeeEntity.DOB = employeeViewModel.DOB;
                existingEmployeeEntity.DOE = employeeViewModel.DOE;
                existingEmployeeEntity.Phone = employeeViewModel.Phone;
                existingEmployeeEntity.Address = employeeViewModel.Address;
                existingEmployeeEntity.Salary = employeeViewModel.Salary;
                existingEmployeeEntity.Gender = employeeViewModel.Gender;
                existingEmployeeEntity.Email = employeeViewModel.Email;
                existingEmployeeEntity.DOR = employeeViewModel.DOR;
                existingEmployeeEntity.UpdatedAt = DateTime.Now;
                existingEmployeeEntity.UpdatedBy = "System";
                existingEmployeeEntity.IpAddress = NetworkHelper.GetMachinePublicIP();
                existingEmployeeEntity.DepartmentId = employeeViewModel.DepartmentId;
                existingEmployeeEntity.PositionId = employeeViewModel.PositionId;

CloudHRMS/Controllers/ShiftController.cs
using CloudHRMS.DAO;
using CloudHRMS.Models.Entities;
using CloudHRMS.Models.ViewModels;
using CloudHRMS.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers
{
    public class ShiftController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public ShiftController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize(Roles = "HR")]
        public IActionResult Entry()
        {
            bindAttendancePolicyData();
            return View();
        }

        private void bindAttendancePolicyData()
        {
            IList<AttendancePolicyViewModel> attendancePolicies = _dbContext.AttendancePolicies.Where(w => w.IsActive).Select(s =>
            new AttendancePolicyViewModel
            {
                Id = s.Id,
                Name = s.Name
            }).ToList();
            ViewBag.AttendancePolicies = attendancePolicies;
        }

        [Authorize(Roles = "HR")]

        [HttpPost]
        public IActionResult Entry(ShiftViewModel shiftViewModel)
        {
            try
            {
                ShiftEntity shiftEntity = new ShiftEntity()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = shiftViewModel.Name,
                    InTime = shiftViewModel.InTime,
                    OutTime = shiftViewModel.OutTime,
                    LateAfter = shiftViewModel.LateAfter,
                    EarlyOutBefore = shiftViewModel.EarlyOutBefore,
                    AttendancePolicyId = shiftViewModel.AttendancePolicyId,
                    CreatedBy = "System"
                };
                _dbContext.Shifts.Add(shiftEntity);
                _dbContext.SaveChanges();
                ViewData["Info"] = "Successfully save the record to the system.";
                ViewData["Status"] = true;
            }
            catch (Exception e)
            {
                ViewData["Info"] = "Error occur when the record save to the system." + e.Message;
                ViewData["Status"] = false;
            }
            bindAttendancePolicyData();
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            IList<ShiftViewModel> shifts = (from s in _dbContext.Shifts
                                            join a in _dbContext.AttendancePolicies
                                            on s.AttendancePolicyId equals a.Id
                                            where s.IsActive && a.IsActive
                                            select new ShiftViewModel
                                            {
                                                Id = s.Id,
                                                Name = s.Name,
                                                InTime = s.InTime,
                                                OutTime = s.OutTime,
                                                LateAfter = s.LateAfter,
                                                EarlyOutBefore = s.EarlyOutBefore,
                                                AttendancePolicyInfo = a.Name,
                                            }).ToList();

            return View(shifts);
        }

        [Authorize(Roles = "HR")]
        public IActionResult Edit(string id)
        {
            ShiftViewModel shiftView = _dbContext.Shifts.Where(w => w.Id == id && w.IsActive).Select(s => new ShiftViewModel
            {
                Id = s.Id,
                Name = s.Name,
                InTime = s.InTime,
                OutTime = s.OutTime,
                LateAfter = s.LateAfter,
                EarlyOutBefore = s.EarlyOutBefore,
                AttendancePolicyId = s.AttendancePolicyId,
                CreatedOn = s.CreatedAt,
                UpdatedOn = s.UpdatedAt
            }).FirstOrDefault();
            bindAttendancePolicyData();
            return View(shiftView);
        }

        [Authorize(Roles = "HR")]

        [HttpPost]
        public IActionResult Update(ShiftViewModel shiftViewModel)
        {
            try
            {
                ShiftEntity shiftEntity = _dbContext.Shifts.Find(shiftViewModel.Id);
                shiftEntity.Name = shiftViewModel.Name;
                shiftEntity.InTime = shiftViewModel.InTime;
                shiftEntity.OutTime = shiftViewModel.OutTime;
                shiftEntity.LateAfter = shiftViewModel.LateAfter;
                shiftEntity.EarlyOutBefore = shiftViewModel.EarlyOutBefore;
                shiftEntity.AttendancePolicyId = shiftViewModel.AttendancePolicyId;
                shiftEntity.UpdatedAt = DateTime.Now;
                shiftEntity.UpdatedBy = "System";
                shiftEntity.IpAddress = NetworkHelper.GetMachinePublicIP();
                _dbContext.Shifts.Update(shiftEntity);
                _dbContext.SaveChanges();
                ViewData["Info"] = "Successfully update the record to the system.";
                ViewData["Status"] = true;
            }
            catch (Exception e)
            {
                ViewData["Info"] = "Error occur when the record update to the system." + e.Message;
                ViewData["Status"] = false;
            }
            return RedirectToAction("List");
        }

        [Authorize(Roles = "HR")]
        public IActionResult Delete(string id)
        {
            try
            {
                ShiftEntity shiftEntity = _dbContext.Shifts.Find(id);
                if (shiftEntity != null)
                {
                    shiftEntity.IsActive = false;
                    _dbContext.Shifts.Update(shiftEntity);
                    _dbContext.SaveChanges();
                    TempData["Info"] = "Delete success when delete the record.";
                }
            }
            catch (Exception e)
            {
                TempData["Info"] = "Error occur when delete the record." + e.Message;
            }
            return RedirectToAction("List");
        }
    }
}

CloudHRMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CloudHRMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CloudHRMS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
    <!--JQuery Plugin-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--sweetalert 2-->
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <!--toastr-->
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CloudHRMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Position" asp-action="List">Position</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Department" asp-action="List">Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Employee" asp-action="List">Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Shift" asp-action="List">Shift</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="ShiftAssign" asp-action="List">Shift Assign</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="AttendancePolicy" asp-action="List">Attendance Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="DailyAttendance" asp-action="List">Daily Attendance</a>
                            </li>
                        }
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CloudHRMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--for Datatables.NET Plugin-->
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <!--sweetalert2-->
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--toastr-->
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CloudHRMS/Views/Shared/_LayoutEmployee.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CloudHRMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CloudHRMS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
    <!--JQuery Plugin-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--sweetalert 2-->
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <!--toastr-->
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CloudHRMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Position" asp-action="List">Position</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Department" asp-action="List">Department</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Employee" asp-action="List">Employee</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Shift" asp-action="List">Shift</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="ShiftAssign" asp-action="List">Shift Assign</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="AttendancePolicy" asp-action="List">Attendance Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="DailyAttendance" asp-action="List">Daily Attendance</a>
                            </li>
                        }
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - CloudHRMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--for Datatables.NET Plugin-->
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <!--sweetalert2-->
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <!--toastr-->
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>