CloudHRMS/Models/ViewModels/PayrollViewModel.cs
namespace CloudHRMS.Models.ViewModels
{
    public class PayrollViewModel
    {
        public string Id { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string EmployeeId { get; set; }
        public string DepartmentId { get; set; }
        public decimal IncomeTax { get; set; }
        public decimal GrossPay { get; set; }
        public decimal NetPay { get; set; }
        public decimal Allowance { get; set; }
        public decimal Deduction { get; set; }
        public string EmployeeInfo { get; set; }
        public decimal BasicSalary { get; set; }
        public string DepartmentInfo { get; set; }
        public decimal AttendanceDays { get; set; }
        public decimal AttendanceDeduction { get; set; }
    }
}

CloudHRMS/Controllers/PayrollController.cs
using CloudHRMS.DAO;
using CloudHRMS.Models.Entities;
using CloudHRMS.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers
{
    public class PayrollController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public PayrollController(ApplicationDbContext applicationDbContext)
        {
            this._applicationDbContext = applicationDbContext;
        }
        public IActionResult List()
        {
            //mapper.map<source,destination>(dataList);
            //_mapper.Map<List<PayrollEntity>,List<PayrollViewModel>>(_applicationDbContext.Payrolls.ToList())
            List<PayrollViewModel> payrollViews = (from p in _applicationDbContext.Payrolls
                                                   join e in _applicationDbContext.Employees
                                                   on p.EmployeeId equals e.Id
                                                   join d in _applicationDbContext.Departments
                                                   on e.DepartmentId equals d.Id
                                                   select new PayrollViewModel
                                                   {
                                                       Id = p.Id,
                                                       FromDate = p.FromDate,
                                                       ToDate = p.ToDate,
                                                       EmployeeInfo = e.No + "/" + e.FullName,
                                                       BasicSalary = e.Salary,
                                                       DepartmentInfo = d.Code + "/" + d.Description,
                                                       GrossPay = p.GrossPay,
                                                       NetPay = p.NetPay,
                                                       AttendanceDays = p.AttendanceDays,
                                                       AttendanceDeduction = p.AttendanceDeduction,
                                                       Allowance = p.Allowance,
                                                       Deduction = p.Deduction,
                                                       IncomeTax = p.IncomeTax,
                                                   }).ToList();
            return View(payrollViews);
        }
        public IActionResult PayrollProcess()
        {
            ViewBag.Employees = (_applicationDbContext.Employees.ToList());
            ViewBag.Departments = (_applicationDbContext.Departments.ToList());
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "HR")]
        public IActionResult PayrollProcess(PayrollProcessViewModel ui)
        {
            try
            {
                List<AttendanceMasterCalculatedData> attendanceMasterCalculatedData = new List<AttendanceMasterCalculatedData>();
                if (ui.DepartmentId != null)
                {
                    //HR,01-03-2024 to 31-03-2024
                    List<AttendanceMasterEntity> attendances = _applicationDbContext.AttendanceMasters.Where(w => w.DepartmentId == ui.DepartmentId && (w.AttendanceDate.ToUniversalTime() <= ui.ToDate.ToUniversalTime())).OrderBy(o => o.AttendanceDate).ToList();
                    List<AttendanceMasterEntity> distinctEmployees = attendances.DistinctBy(e => e.EmployeeId).ToList();
                    foreach (AttendanceMasterEntity distinctEmployee in distinctEmployees)
                    {
                        AttendanceMasterCalculatedData calculatedData = new AttendanceMasterCalculatedData();
                        calculatedData.DepartmentId = distinctEmployee.DepartmentId;
                        calculatedData.EmployeeId = distinctEmployee.EmployeeId;
                        calculatedData.FromDate = ui.FromDate.ToUniversalTime();
                        calculatedData.ToDate = ui.ToDate.ToUniversalTime();
                        calculatedData.BasicPay = _applicationDbContext.Employees.Find(distinctEmployee.EmployeeId).Salary;
                        calculatedData.LateCount = attendances.Where(w => w.EmployeeId == distinctEmployee.EmployeeId && w.IsLate && (w.AttendanceDate.ToUniversalTime() >= ui.FromDate.ToUniversalTime() && w.AttendanceDate <= ui.ToDate.ToUniversalTime())).Count();
                        calculatedData.EarlyOutCount = attendances.Where(w => w.EmployeeId == distinctEmployee.EmployeeId && w.IsEarlyOut && (w.AttendanceDate.ToUniversalTime() >= ui.FromDate.ToUniversalTime() && w.AttendanceDate <= ui.ToDate.ToUniversalTime())).Count();
                        calculatedData.LeaveCount = attendances.Where(w => w.EmployeeId == distinctEmployee.EmployeeId && w.IsLeave && (w.AttendanceDate.ToUniversalTime() >= ui.FromDate.ToUniversalTime() && w.AttendanceDate.ToUniversalTime() <= ui.ToDate.ToUniversalTime())).Count();
                        calculatedData.AttendanceDays = attendances.Where(w => w.EmployeeId == distinctEmployee.EmployeeId && w.IsLeave == false && (w.AttendanceDate.ToUniversalTime() >= ui.FromDate.ToUniversalTime() && w.AttendanceDate.ToUniversalTime() <= ui.ToDate.ToUniversalTime())).Count();
                        attendanceMasterCalculatedData.Add(calculatedData);
                    }
                    List<PayrollEntity> payrolls = CalculatePayroll(attendanceMasterCalculatedData);
                    _applicationDbContext.Payrolls.AddRange(payrolls);
                    _applicationDbContext.SaveChanges();
                    TempData["Info"] = "successfully save a record to the system";
                }
            }
            catch (Exception ex)
            {
                TempData["Info"] = "Error occur when  saving a record  to the system";
            }
            return RedirectToAction("list");
        }

        private List<PayrollEntity> CalculatePayroll(List<AttendanceMasterCalculatedData> attendanceMasterCalculatedData)
        {
            List<PayrollEntity> payrolls = new List<PayrollEntity>();
            decimal incomeTax = 2000, allowance = 30000, deduction = 10000;
            int workingDays = 30;
            foreach (AttendanceMasterCalculatedData calculatedData in attendanceMasterCalculatedData)
            {
                PayrollEntity payroll = new PayrollEntity();
                payroll.Id = Guid.NewGuid().ToString();
                payroll.FromDate = calculatedData.FromDate.ToUniversalTime();
                payroll.ToDate = calculatedData.ToDate.ToUniversalTime();
                payroll.EmployeeId = calculatedData.EmployeeId;
                payroll.DepartmentId = calculatedData.DepartmentId;
                payroll.IncomeTax = incomeTax;
                decimal PayPerDay = (calculatedData.BasicPay / workingDays);//500000/30 >> 16,666.66666666667
                payroll.AttendanceDeduction = CalculateAttendanceDeductionByAttendancePolicy(calculatedData.EmployeeId, PayPerDay, calculatedData.LateCount, calculatedData.EarlyOutCount);
                payroll.GrossPay = ((PayPerDay) * calculatedData.AttendanceDays) + allowance - payroll.AttendanceDeduction - deduction;
                payroll.NetPay = payroll.GrossPay - payroll.IncomeTax;
                payroll.Allowance = allowance;
                payroll.Deduction = deduction;
                payroll.AttendanceDays = calculatedData.AttendanceDays;
                payroll.CreatedBy = "System";
                payrolls.Add(payroll);
            }
            return payrolls;
        }

        private decimal CalculateAttendanceDeductionByAttendancePolicy(string EmployeeId, decimal PayPerDay, int lateCount, int earlyOutCount)
        {
            decimal attendanceDeduction = 0;
            var attendancePolicy = (from ap in _applicationDbContext.AttendancePolicies
                                    join s in _applicationDbContext.Shifts
                                    on ap.Id equals s.AttendancePolicyId
                                    join sa in _applicationDbContext.ShiftAssigns
                                    on s.Id equals sa.ShiftId
                                    where sa.EmployeeId == EmployeeId
                                    select ap).FirstOrDefault();
            if (attendancePolicy != null)
            {
                if (lateCount > attendancePolicy.NumberOfLateTime || attendancePolicy?.NumberOfEarlyOutTime < earlyOutCount)
                {
                    attendanceDeduction = attendancePolicy?.DeductionInAmount ?? 0;
                }
                if (attendancePolicy?.DeductionInDay > 0)
                {
                    attendanceDeduction += (PayPerDay * attendancePolicy?.DeductionInDay) ?? 0;
                }
            }
            return attendanceDeduction;
        }
        /*
        public IActionResult PayrollDetailReport()
        {
            ViewBag.Employees = _mapper.Map<List<EmployeeEntity>, List<EmployeeViewModel>>(_applicationDbContext.Employees.ToList());
            ViewBag.Departments = _mapper.Map<List<DepartmentEntity>, List<DepartmentViewModel>>(_applicationDbContext.Departments.ToList());
            return View();
        }
        public IActionResult PayrollDetailReportByPayrollMonth(DateTime fromDate, DateTime toDate, string employeeId, string departmentId)
        {
            List<PayrollDetail> payrollDetails = (from p in _applicationDbContext.Payrolls
                                                  join e in _applicationDbContext.Employees
                                                  on p.EmployeeId equals e.Id
                                                  join d in _applicationDbContext.Departments
                                                  on e.DepartmentId equals d.Id

CloudHRMS/Views/Payroll/List.cshtml
@model List<PayrollViewModel>
<h1>Payroll Information for each employee</h1>
@if (TempData["info"] != null)
{
    <div class="alert alert-info">
        @TempData["info"]
    </div>
}
<table class="table table-bordered table-striped" id="PayrollTable">
    <thead>
        <tr>
            <th scope="col">#</th>
            <td scope="col">FromDate</td>
            <td scope="col">ToDate</td>
            <td scope="col">Employee</td>
            <td scope="col">Department</td>
            <td scope="col">Basic Salary</td>
            <td scope="col">IncomeTax</td>
            <td scope="col">GrossPay</td>
            <td scope="col">Allowance</td>
            <td scope="col">Deduction</td>
            <td scope="col">Attendance Deduction</td>
            <td scope="col">Net Pay</td>
            <td scope="col">Attendance Days</td>
            @if (User.IsInRole("HR"))
            {
                <th scope="col">Actions</th>
            }
        </tr>
    </thead>
    <tbody>
        @{
            int index = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@index</th>
                <td>@item.FromDate.ToString("dd-MM-yyyy")</td>
                <td>@item.ToDate.ToString("dd-MM-yyyy")</td>
                <td>@item.EmployeeInfo</td>
                <td>@item.DepartmentInfo</td>
                <td>@item.BasicSalary</td>
                <td>@item.IncomeTax</td>
                <td>@item.GrossPay</td>
                <td>@item.Allowance</td>
                <td>@item.Deduction</td>
                <td>@item.AttendanceDeduction</td>
                <td>@item.NetPay</td>
                <td>@item.AttendanceDays</td>
                @if (User.IsInRole("HR"))
                {
                    <td>
                        <div class="btn btn-group">
                            <a href="#" class="btn btn-primary" role="button">Edit</a>
                            <a asp-action="Delete" asp-controller="Payroll" asp-route-id="@item.Id" onclick="return confirm('are you sure to delete this record?');" class="btn btn-danger" role="button"> Delete</a>
                        </div>
                    </td>
                }
            </tr>
            index++;
        }
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $("#PayrollTable").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#PayrollTable_wrapper .col-md-6:eq(0)');
    });
</script>

CloudHRMS/Views/Payroll/PayrollProcess.cshtml
<div>
    <h1>Payroll Process</h1>
    @if (ViewBag.info != null)
    {
        <div class="alert alert-danger">
            @ViewBag.info
        </div>
    }
    <form action="/payroll/payrollprocess" method="post">
        <div class="mb-3">
            <label for="FromDate" class="form-label">From Date</label>
            <input type="date" name="FromDate" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="ToDate" class="form-label">To Date</label>
            <input type="date" name="ToDate" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="DepartmentId" class="form-label">Department</label>
            <select name="DepartmentId" class="form-select">
                <option value="x" selected>[select department]</option>
                @foreach (var d in ViewBag.Departments)
                {
                    <option value="@d.Id">@d.Description</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <label for="EmployeeId" class="form-label">Employee</label>
            <select name="EmployeeId" class="form-select">
                <option value="x" selected>[select employee]</option>
                @foreach (var e in ViewBag.Employees)
                {
                    <option value="@e.Id">@e.No / @e.FullName</option>
                }
            </select>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Payroll Process</button>
            <button class="btn btn-danger">Cancel</button>
        </div>
    </form>
</div>